spring.datasource.url=jdbc:mysql://localhost:3306/ai_email_writer
spring.datasource.username=root
spring.datasource.password=Mohan109@

openrouter.api.key=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
java.net.preferIPv4Stack=true